Repository DaemonEngine/Daemon, pull requests merged in 2020-04, with the labels that each got.

#311 Remove unused AES256 decryption
  src/engine/framework/Crypto.cpp
Labels: cleanup

#282 Add layout to serverinfo
  src/engine/server/sv_init.cpp
Labels: bug

#308 renderer: drop r_collapseStages, do not allow to not collapse material stages
  src/engine/renderer/tr_init.cpp
  src/engine/renderer/tr_local.h
  src/engine/renderer/tr_shader.cpp
Labels: A-Renderer, cleanup

#312 polylib: workaround MAX_POINTS_ON_WINDING in ChopWindingInPlace, ref #169
  src/common/cm/cm_polylib.cpp
Labels: bug

#315 map meta lookup: only check for map in packs starting with “map-” prefix, fix #285
  src/engine/qcommon/files.cpp
Labels: A-VFS, bug

#307 renderer/tr_shader: introduce engine-agnostic normalFormat material stage keyword
  src/engine/renderer/glsl_source/reliefMapping_fp.glsl
  src/engine/renderer/tr_local.h
  src/engine/renderer/tr_shade.cpp
  src/engine/renderer/tr_shader.cpp
Labels: A-Renderer, feature request
